language: node_js
node_js:
  - "14.3.0"

env:
  global:
    - DOCKER_COMPOSE_VERSION: 1.26.2
    - PGDATABASE: battle_academia
    - PGPORT: 5432
    - PGUSER: docker
    - PGPASSWORD: docker

services:
  - docker

jobs:
  include:
    - stage: api tests
      before_install:
        # Download specific version of Docker-Compose
        - npm rebuild
        - sudo rm /usr/local/bin/docker-compose
        - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
        - chmod +x docker-compose
        - sudo mv docker-compose /usr/local/bin
      install:
        - npm install newman
      before_script:
        # Check dependencies and config
        - node --version
        - npm --version
        - node_modules/.bin/newman --version
        - docker --version
        - docker-compose --version
        - docker-compose config
        - ls -lah
        # Build containers
        - docker-compose up -Vd --build
        - docker-compose ps
        - >
          docker-compose exec db
          /bin/bash -c "until psql -l -U ${PGUSER}; do echo 'db unavailable. sleeping'; sleep 1; done"
        - docker-compose exec db ls
        - docker-compose logs db
      script:
        - >
          node_modules/.bin/newman 
          run server/api/postman-collections/battle-academia_placement-exam_api-test.postman-collection.json
          -e server/api/postman-collections/battle-academia_placement-exam_docker.postman-environment.json
          -r cli
      after_script:
        - docker-compose down
