version: '3.8'

services:
  api:
    build: ./server
    environment:
      - PGHOST=db
      - PGDATABASE=battle_academia
      - PGUSER=docker
      - PGPASSWORD=docker
      - PGPORT=5432
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:12.3-alpine
    restart: always
    environment:
      - POSTGRES_DB=battle_academia
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"
    volumes:
      - ./server/db/scripts:/docker-entrypoint-initdb.d
