version: '3.8'

services:
  api:
    environment:
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}

  db:
    user: ${TRAVIS_UID:?You must do 'export TRAVIS_UID' to launch}:${TRAVIS_GID:?You must do 'export TRAVIS_GID' to launch}
    environment:
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
