version: '3.8'

services:
  api:
    build: ./server
    environment:
      - PGHOST=db
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    restart: always
    ports:
      - "5432:5432"
