version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - api

  api:
    build: ./server
    environment:
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:12.3-alpine
    restart: always
    environment:
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./server/db/scripts:/docker-entrypoint-initdb.d

  api-test:
    image: dannydainton/htmlextra
    entrypoint: [""]
    command: newman run -v
    volumes:
      - ./server/api/postman-collections:/etc/newman
    depends_on:
      - api
