version: '3.8'

services:
  api:
    build: ./server
    environment:
      - PGHOST=db
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:12.3-alpine
    volumes:
      - ./server/db/scripts:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "5432:5432"
